### ISSUE TITLE
动画结束前再次滑动会卡死

### ISSUE THREAD

**Issue by mug1s** [lilei644/LLSlideMenu#10]
![qq20160816-0](https://cloud.githubusercontent.com/assets/14891016/17686194/116bd1be-639d-11e6-9b3d-4b2bb2ff1e68.png)
像这样。

**Comment by lilei644** [comment]
多谢关注！
已修复bug，您有时间的时候可以尝试使用一下！谢谢！

**Comment by kingwangboss** [comment]
当我在leftview上点击一个按钮跳到其他控制器，如果快速返回leftview将关闭不了，如果等一会儿返回leftview可以关闭。

**Comment by lilei644** [comment]
@kingwangboss 多谢！经调试已找到原因，由于页面跳转导致动画结束的回调未调用。现已修复升级并发布，欢迎试用!  :)
