### ISSUE TITLE
Can it slide in from left?

### ISSUE THREAD

**Issue by tonymuu** [lilei644/LLSlideMenu#11]
Could you please make so it supports sliding in from left? Thanks

**Comment by rixjafri** [comment]
Yes you can ... find the following function 
- (void)swipeLeftHandle:(UIScreenEdgePanGestureRecognizer *)recognizer{

and replace the following code 

if (_slideMenu.ll_isOpen) {
        return;
}

with this

if (_slideMenu.ll_isOpen) {
        [_slideMenu ll_closeSlideMenu];
        return;
 }

**Comment by tonymuu** [comment]
Great! I'll test it as soon as possible and will let you know :)

**Comment by rixjafri** [comment]
yeah sure :)

**Comment by tonymuu** [comment]
Hi, my bad! I think it defaults sliding in from the left, but how do I make it slide in from the right side? Thanks.

**Comment by lilei644** [comment]
Sorry, the current version does not support the slide from the right, if you want to, you can modify the direction of the LLDisplayLayer drawing and coordinate positions, as well as touch gestures listening :)

**Comment by tonymuu** [comment]
If I want to contribute to this repo, do I create a fork and then do all the changes locally, and then create a pull request?

**Comment by lilei644** [comment]
Yes, of course!   :)

**Comment by tonymuu** [comment]
Great! I'll try to start working on it asap :)
