### ISSUE TITLE
侧滑无法返回

### ISSUE THREAD

**Issue by yimouleng** [lilei644/LLSlideMenu#2]
Xcode7.1    模拟器 使用iphone6    9.1 系统，  侧滑菜单弹出没有问题，  但是 滑动返回时出现卡在返回动画上，  程序不会crash，但也没有任何反应。

**Comment by lilei644** [comment]
谢谢提醒，暂时只考虑了滑动打开，打开之后直接点击空白处就可关闭，滑动关闭方面没做处理，我调试下，后续把这个功能加上去！

**Comment by lilei644** [comment]
刚才调试了下，卡住的原因是因为动画还没结束又再次滑动屏幕，已修复，谢谢关注！
