### ISSUE TITLE
请问怎么控制这个控件弹出时候的过渡时间，特别使用cocoapods的时候

### ISSUE THREAD

**Issue by DexSinis** [lilei644/LLSlideMenu#3]
请问怎么控制这个控件弹出时候的过渡时间，特别使用cocoapods的时候

**Comment by lilei644** [comment]
谢谢关注！控件的弹性动画是由阻尼振动的原理完成的，所以不能直接准确的设置动画时间，看了你提的问题之后我拓展出了动画的属性参数，可自定义设置
_slideMenu.ll_springDamping = 20;       // 阻力
_slideMenu.ll_springVelocity = 15;      // 速度
_slideMenu.ll_springFramesNum = 60;     // 关键帧数量
这几个是默认值，你可以试试改变参数调试下观察动画弹性效果和时间的改变。
新版已发布到cocoapods,版本1.0.3

**Comment by DexSinis** [comment]
thank you
