### ISSUE TITLE
How do you add links to the menu? 

### ISSUE THREAD

**Issue by trub** [lilei644/LLSlideMenu#5]
Right now the links in the menu are formatted with a text label. Would you be willing to update this so that those are actually default links that segue to a new view controller?

 Please see attached image for clarification.
<img width="869" alt="screen shot 2015-12-07 at 6 41 50 pm" src="https://cloud.githubusercontent.com/assets/5760354/11646380/5d4145bc-9d12-11e5-854f-021e6819ff8c.png">

**Comment by lilei644** [comment]
Thank you for your attention! This project mainly depends on the flexibility of the animation demo, showing that the view is completely customized, you can add any links and components!
