### ISSUE TITLE
左滑手势失去响应

### ISSUE THREAD

**Issue by lynulzy** [lilei644/LLSlideMenu#6]
复现场景：Demo中左滑->出现slidemenu,->向上滑动

页面卡死，如图：

![](http://ww1.sinaimg.cn/large/77cf5fafjw1eyujib5ri7j20pm1b2tdo.jpg)

**Comment by lynulzy** [comment]
另外，个人赶紧，既然是“**菜单”控件，那么菜单的功能还是要有的，但是目前貌似没有看到有关菜单事件的有效封装。

但是仍然感谢作者的付出。THX

**Comment by lilei644** [comment]
感谢关注！新版Demo中已修复左滑卡死问题，而且本身不支持滑动关闭的功能，点击右侧空白区域即可关闭。本控件主要侧重的是弹性效果的关键帧动画，所以在菜单上没做封装，属于完全自定义部分！

**Comment by lynulzy** [comment]
好的，多谢！
